"""
Code generation utilities
"""
import os
import logging
from typing import Dict, Any
from pathlib import Path

logger = logging.getLogger(__name__)

class CodeGenerator:
    """Helper for code generation tasks"""
    
    @staticmethod
    def create_requirements_file(dependencies: list) -> str:
        """Create requirements.txt content"""
        content = "# Generated by Autonomous Coding Partner\n"
        content += "# Python dependencies\n\n"
        content += "\n".join(sorted(set(dependencies)))
        return content
    
    @staticmethod
    def create_gitignore() -> str:
        """Create .gitignore file"""
        return """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
ENV/
env.bak/
venv.bak/

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Virtual Environment
.venv/
"""
    
    @staticmethod
    def create_dockerfile(project_type: str = "python") -> str:
        """Create Dockerfile based on project type"""
        if project_type == "python":
            return """FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "main.py"]
"""
        elif project_type == "fastapi":
            return """FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
"""
        else:
            return """# Dockerfile for your project
# Add your Docker configuration here
"""